### Overview

Splitting of SCAN-B HiSeq raw and TPM-normalized counts dataset into 80% training set and 20% test set.

Note: These datasets are with PAM50 genes as features.

In [1]:
import pandas as pd
import numpy as np
import random
from sklearn.model_selection import train_test_split

### 1. Import and Prepare SCANB Hiseq PAM50 Raw and TPM Counts Data

In [2]:
# import scanb hiseq raw counts of PAM50 genes
scanb_raw_data = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_cleaned_data/pam50genes_raw_counts_subtype_scanb_hiseq.csv",
                       header=0, index_col=0)

In [3]:
# import scanb hiseq tpm counts of PAM50 genes
scanb_tpm_data = pd.read_csv("C:/Users/User/Documents/master_thesis_project_analysis/datasets/SCANB_GSE202203/scanb_cleaned_data/pam50genes_tpm_counts_subtype_scanb_hiseq.csv",
                       header=0, index_col=0)

In [10]:
# check whether the indices and columns match
print(scanb_raw_data.index.equals(scanb_tpm_data.index))
print(scanb_raw_data.columns.equals(scanb_tpm_data.columns))

# check whether the subtype order matches
print(scanb_raw_data['subtype'].tolist() == scanb_tpm_data['subtype'].tolist())

True
True
True

In [6]:
print(scanb_raw_data.shape)
print(scanb_tpm_data.shape)

(2755, 51)
(2755, 51)

In [7]:
scanb_raw_data.head(2)

,ENSG00000133627,ENSG00000011426,ENSG00000107262,ENSG00000171791,ENSG00000089685,ENSG00000106605,ENSG00000134057,ENSG00000105173,ENSG00000117399,ENSG00000094804,...,ENSG00000092621,ENSG00000164611,ENSG00000171848,ENSG00000104332,ENSG00000141424,ENSG00000151715,ENSG00000176890,ENSG00000175063,ENSG00000077152,subtype
S000001,152,129,2947,3038,165,2951,209,16,125,137,...,1203,92,212,382,43926,1855,356,81,93,LumA
S000002,382,1304,283,311,1060,426,848,56,2552,445,...,3789,526,1437,9125,4558,11,922,806,409,Basal

In [8]:
scanb_tpm_data.head(2)

,ENSG00000133627,ENSG00000011426,ENSG00000107262,ENSG00000171791,ENSG00000089685,ENSG00000106605,ENSG00000134057,ENSG00000105173,ENSG00000117399,ENSG00000094804,...,ENSG00000092621,ENSG00000164611,ENSG00000171848,ENSG00000104332,ENSG00000141424,ENSG00000151715,ENSG00000176890,ENSG00000175063,ENSG00000077152,subtype
S000001,4.744837,2.514090,59.722866,30.418488,4.637924,192.699161,11.074169,0.565211,5.142068,3.182332,...,45.150858,8.263110,4.469104,5.899850,884.911039,60.622748,16.553019,6.629500,6.986735,LumA
S000002,35.945814,57.077521,18.149436,8.811815,71.174734,67.966579,74.532939,4.787328,264.242629,26.790985,...,351.452896,111.701446,76.825305,356.584546,234.043325,0.888083,108.975417,187.463419,77.493399,Basal

In [9]:
# check subtype proportion in raw and tpm datasets
print('Raw dataset:')
print(scanb_raw_data['subtype'].value_counts())

print('\nTPM dataset:')
print(scanb_tpm_data['subtype'].value_counts())

Raw dataset:
subtype
LumA     1398
LumB      818
Basal     288
Her2      251
Name: count, dtype: int64

TPM dataset:
subtype
LumA     1398
LumB      818
Basal     288
Her2      251
Name: count, dtype: int64

In [11]:
# separate counts and labels
scanb_raw_counts = scanb_raw_data.iloc[:, 0:50]
scanb_tpm_counts = scanb_tpm_data.iloc[:, 0:50]
scanb_subtype = scanb_raw_data.iloc[:, [50]]

### 2. Split the SCAN-B Hiseq Dataset into 80% Training and 20% Test

In [12]:
# note: initialize randomness before splitting
seed = 42
random.seed(seed)
np.random.seed(seed)

# split scanb raw and tpm data into 80% training and 20% test sets
scanb_raw_train, scanb_raw_test, scanb_raw_subtype_train, scanb_raw_subtype_test = train_test_split(scanb_raw_counts, scanb_subtype, test_size=0.20, 
                                                                                            stratify=scanb_subtype, shuffle=True, random_state=seed)

scanb_tpm_train, scanb_tpm_test, scanb_tpm_subtype_train, scanb_tpm_subtype_test = train_test_split(scanb_tpm_counts, scanb_subtype, test_size=0.20,
                                                                                            stratify=scanb_subtype, shuffle=True, random_state=seed)

In [16]:
# check whether the indices match between the raw and tpm datasets
print(scanb_raw_train.index.equals(scanb_tpm_train.index))
print(scanb_raw_train.index.equals(scanb_raw_subtype_train.index))
print(scanb_raw_test.index.equals(scanb_tpm_test.index))
print(scanb_raw_test.index.equals(scanb_raw_subtype_test.index))

True
True
True
True

In [13]:
# check whether the subtype order matches between raw and tpm training and test sets
print(scanb_raw_subtype_train['subtype'].tolist() == scanb_tpm_subtype_train['subtype'].tolist())
print(scanb_raw_subtype_test['subtype'].tolist() == scanb_tpm_subtype_test['subtype'].tolist())

True
True

In [17]:
print(scanb_raw_train.shape)
print(scanb_tpm_train.shape)
print(scanb_raw_subtype_train.shape)
print(scanb_raw_test.shape)
print(scanb_tpm_test.shape)
print(scanb_raw_subtype_test.shape)

(2204, 50)
(2204, 50)
(2204, 1)
(551, 50)
(551, 50)
(551, 1)

In [19]:
# check subtype proportion in training and test sets
print('Training set:')
print(scanb_raw_subtype_train['subtype'].value_counts())

print('\nTest set:')
print(scanb_raw_subtype_test['subtype'].value_counts())

Training set:
subtype
LumA     1119
LumB      654
Basal     230
Her2      201
Name: count, dtype: int64

Test set:
subtype
LumA     279
LumB     164
Basal     58
Her2      50
Name: count, dtype: int64

In [20]:
# merge counts and subtype labels for raw count training and test sets
scanb_raw_label_train = pd.merge(scanb_raw_train, scanb_raw_subtype_train, left_index=True, right_index=True)
scanb_raw_label_test = pd.merge(scanb_raw_test, scanb_raw_subtype_test, left_index=True, right_index=True)

# merge counts and subtype labels for tpm count training and test sets
# note: subtype labels are same for both raw and tpm counts
scanb_tpm_label_train = pd.merge(scanb_tpm_train, scanb_raw_subtype_train, left_index=True, right_index=True)
scanb_tpm_label_test = pd.merge(scanb_tpm_test, scanb_raw_subtype_test, left_index=True, right_index=True)

In [21]:
# add dataset column in SCAN-B GSE202203 training and test sets for both raw and tpm counts
scanb_raw_label_train['dataset'] = 'SCAN-B Illumina Hiseq'
scanb_tpm_label_train['dataset'] = 'SCAN-B Illumina Hiseq'
scanb_raw_label_test['dataset'] = 'SCAN-B Illumina Hiseq'
scanb_tpm_label_test['dataset'] = 'SCAN-B Illumina Hiseq'

In [25]:
# subtype proportion percentage in scanb hiseq training set
scanb_train_classprop = scanb_raw_label_train['subtype'].value_counts()
scanb_train_class = scanb_train_classprop.index.tolist()
scanb_train_classCount = scanb_train_classprop.values.tolist()

for i in range(len(scanb_train_class)):
    percent_train = round((scanb_train_classCount[i]/scanb_raw_label_train.shape[0])*100,2)
    print(f"{scanb_train_class[i]}: {scanb_train_classCount[i]} ({percent_train}%)")

LumA: 1119 (50.77%)
LumB: 654 (29.67%)
Basal: 230 (10.44%)
Her2: 201 (9.12%)

In [26]:
# subtype proportion percentage in scanb hiseq test set
scanb_test_classprop = scanb_raw_label_test['subtype'].value_counts()
scanb_test_class = scanb_test_classprop.index.tolist()
scanb_test_classCount = scanb_test_classprop.values.tolist()

for i in range(len(scanb_test_class)):
    percent_test = round((scanb_test_classCount[i]/scanb_raw_label_test.shape[0])*100,2)
    print(f"{scanb_test_class[i]}: {scanb_test_classCount[i]} ({percent_test}%)")

LumA: 279 (50.64%)
LumB: 164 (29.76%)
Basal: 58 (10.53%)
Her2: 50 (9.07%)

In [42]:
# # save the files
# gse_raw_label_train.to_csv('SCANB_HiSeq_pam50gene_raw_counts_subtype_train_80.csv')
# gse_tpm_label_train.to_csv('SCANB_HiSeq_pam50gene_tpm_counts_subtype_train_80.csv')
# gse_raw_label_test.to_csv('SCANB_HiSeq_pam50gene_raw_counts_subtype_test_20.csv')
# gse_tpm_label_test.to_csv('SCANB_HiSeq_pam50gene_tpm_counts_subtype_test_20.csv')